options:
  auto-update: true
  item-refresh-delay: 150
  item-nametags: true
  chunk-notifications: false
  money-symbol: '$'
shops:
  prefix: '&8[&6Shop&8]'
  prefix-infinite: '&8[&4AdminShop&8]'
  buy-menu: false
  max-price: 1000000000000.0
markets:
  enabled: false
  prefix: '&8[&aMarket&8]'
  prefix-infinite: '&8[&4AdminShop&8]'
  buy-menu: true
marketstand:
  prefix-available: '&8[&aMarket&8]'
  prefix-unavailable: '&8[&4Market&8]'
  max-days: 7