name: QuickMarket
version: ${project.version}
author: TheBusyBiscuit
website: http://thebusybiscuit.github.io/
depend: [Vault]
softdepend: [PrisonUtils]

main: io.github.thebusybiscuit.quickmarket.QuickMarket
api-version: 1.13

permissions:
  QuickMarket.shop.infinite:
    description: Allows you to make infinite Shops
    default: op
  QuickMarket.shop.bypass:
    description: Allows you to modify other Shops
    default: op
  QuickMarket.market.admin:
    description: Allows you to create/delete Marketstands
    default: op
  QuickMarket.shop.create:
    description: Allows you to create Shops
    default: true