name: QuickMarket
version: 1.3
author: mrCookieSlime
website: http://thebusybiscuit.github.io/
depend: [Vault]
softdepend: [CS-CoreLib, PrisonUtils]

main: me.mrCookieSlime.QuickMarket.QuickMarket

api-version: 1.13

permissions:
  QuickMarket.shop.infinite:
    description: Allows you to make infinite Shops
    default: op
  QuickMarket.shop.bypass:
    description: Allows you to modify other Shops
    default: op
  QuickMarket.market.admin:
    description: Allows you to create/delete Marketstands
    default: op